#!/bin/sh

# Exit immediately if a simple command exits with a nonzero exit value
set -e

# Cleanup
rm -rf output

# Build the Docker image
docker build -t nodeimage .

# Generate the node_modules tarball generated by using npm clean-install
docker-compose run --rm generate1

# Generate the node_modules tarball generated by using npm install withput package-lock.json
docker-compose run --rm generate2

# Compare the two tarballs. This will print their respective SHA1 checksums
docker-compose run --rm compare
